sonar.projectKey=Brain-Link-Team_WORKING-WITH-LAYOUTS-BORDERLAYOUTS-Task-2
sonar.host.url=https://placentary-conjunctively-george.ngrok-free.dev
sonar.login=YOUR_SONAR_TOKEN_HERE
sonar.sources=src
sonar.java.binaries=out