sonar.projectKey=Brain-Link-Team_WORKING-WITH-LAYOUTS-BORDERLAYOUTS-Task-2
sonar.host.url=https://placentary-conjunctively-george.ngrok-free.dev
sonar.login=sqp_f5fdefafafc28137a5e068f2f1efe685e06fbb46
sonar.sources=src
sonar.java.binaries=out
