sonar.projectKey=Brain-Link-Team_WORKING-WITH-LAYOUTS-BORDERLAYOUTS-Task-2
sonar.host.url=https://placentary-conjunctively-george.ngrok-free.dev
sonar.token=sqp_f5fdefafafc28137a5e068f2f1efe685e06fbb46
sonar.sources=.
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
